---
# Configure the source mysql database for replication

- name: Add replication settings to server-id my.cnf for source db
  ini_file:
    path: /etc/mysql/my.cnf
    section: mysqld
    option: server-id
    value: "1"
    backup: yes

- name: Add replication settings to log_bin my.cnf for source db
  ini_file:
    path: /etc/mysql/my.cnf
    section: mysqld
    option: log_bin
    value: /var/log/mysql/mysql-bin.log
    backup: yes

- name: Add replication settings to binlog_do_db my.cnf for source db
  ini_file:
    path: /etc/mysql/my.cnf
    section: mysqld
    option: binlog_do_db
    value: wordpress
    backup: yes

- name: Add sql_mode
  ini_file:
    path: /etc/mysql/my.cnf
    section: mysqld
    option: sql_mode
    value: NO_ENGINE_SUBSTITUTION
    backup: yes

- name: Create replica db user
  mysql_user:
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: replica
    password: "{{ dbpassword}}"
    priv: '*.*:ALL,GRANT'
    host: '%'
    state: present

- name: restart mysql
  shell: service mysql restart
