# Generated by tabular-terraform
variable "vpc-name" {
  description = "Define vpc"
}
variable "resource-group" {
  description = "Define resource group"
}
variable "region" {
  description = "Define region"
}
variable "zone1" {
  description = "Define zone1"
}
variable "zone2" {
  description = "Define zone2"
}
variable "webapptier-subnet-zone1" {
  description = "Define webapptier subnet cidr for zone1"
}
variable "webapptier-subnet-zone2" {
  description = "Define webapptier subnet cidr for zone2"
}
variable "webappserver-name" {
  description = "Define webapp instance name"
}
variable "webappserver-count" {
  description = "Define webapp instance count"
}
variable "profile-webappserver" {
  description = "Define webapp instance profile"
}
variable "image" {
  description = "Define OS image for compute instances"
}
variable "domain" {
  description = "Define domain name"
}
variable "cis-instance-name" {
  description = "Define CIS instance name"
}
variable "dns-name" {
  description = "Define dns name"
}
variable "webapptier-lb-connections" {
  description = "Define number of LB connections in webapptier"
}
variable "webapptier-lb-algorithm" {
  description = "Define  algorithm used for LB in webapptier"
}
variable "onprem-cidr" {
  description = "Define vpn onprem cidr"
}
variable "vpc-id" {
  description = "Get vpc id"
}
variable "group-id" {
  description = "Get resource group id"
}
variable "sshkey-id" {
  description = "Get ssh key id"
}
variable "webapptier-subnet-zone1-id" {
  description = "Get webapptier subnet zone1 id"
}
variable "webapptier-subnet-zone2-id" {
  description = "Get webapptier subnet zone2 id"
}
variable "webapptier-securitygroup-id" {
  description = "Get webapptier security group id"
}
variable "maintenance-securitygroup-id" {
  description = "Get maintenance security group id"
}
