# Generated by buildIT
variable "ibm-centos-stream-9-amd64-12" {
default = "r006-e3db7562-d181-4b6c-b22b-ea8273b75b06"
}
variable "ibm-debian-12-5-minimal-amd64-1" {
default = "r006-b12021ba-221a-4dd6-ac1d-88bc08a48e67"
}
variable "ibm-redhat-9-2-minimal-amd64-3" {
default = "r006-44802d4c-5752-459c-aaed-4227da8fa29c"
}
variable "ibm-rocky-linux-9-3-minimal-amd64-1" {
default = "r006-685ae8f8-56aa-4bb1-a5e1-8b158db76864"
}
variable "ibm-sles-15-5-amd64-2" {
default = "r006-8b5927e5-e446-42d9-9799-e672b1dd60ab"
}
variable "ibm-ubuntu-22-04-4-minimal-amd64-1" {
default = "r006-193d3ae5-17dd-4990-8ac3-ae4c1e87a25c"
}
variable "ubuntu-20-04-4-minimal-amd64-1" {
default = "r006-dd164da8-c4d9-46ba-87c4-03c614f0532c"
}
variable "ibm-windows-server-2022-full-standard-amd64-11" {
default = "r006-56c8ce3e-c0fa-4f87-b675-4c223b35588c"
}
