# Generated by tabular-terraform
variable "centos-8-3-amd64" {
  default = "r006-de4fc543-2ce1-47de-b0b8-b98556a741da"
}
variable "centos-7-9-amd64" {
  default = "r006-13938c0a-89e4-4370-b59b-55cd1402562d"
}
variable "debian-10-8-amd64" {
  default = "r006-0f0c5fd0-d3f0-42a0-bc20-88a59286631e"
}
variable "debian-9-13-amd64" {
  default = "r006-8e4826f3-1394-40cf-af8f-c5e93039935b"
}
variable "redhat-8-3-amd64" {
  default = "r006-c803a85a-e3cf-4f61-bafa-ae1d9e759d15"
}
variable "redhat-7-9-amd64" {
  default = "r006-e279f5d7-fa19-4294-979e-7a6d048fbe71"
}
variable "ubuntu-20-04-amd64" {
  default = "r006-988caa8b-7786-49c9-aea6-9553af2b1969"
}
variable "ubuntu-18-04-amd64" {
  default = "r006-ed3f775f-ad7e-4e37-ae62-7199b4988b00"
}
variable "windows-2019-amd64" {
  default = "r006-7e605d5f-2632-4ed2-a0c1-580af25decd4"
}
variable "windows-2016-amd64" {
  default = "r006-c089c0c5-0789-432a-9666-64e66ad6c9cf"
}
variable "windows-2012-r2-amd64" {
  default = "r006-5ff6bd9a-226e-4c20-8718-2e50906aa249"
}
variable "windows-2012-amd64" {
  default = "r006-5f9568ae-792e-47e1-a710-5538b2bdfca7"
}
