# Generated by buildIT
variable "debian-10-11-minimal-amd64-3" {
default = "r006-577a6665-9958-42f7-a94b-42b81fab1ab5"
}
variable "debian-11-3-minimal-amd64-1" {
default = "r006-f3a6eb33-8b7f-4850-b7b7-cf2f4ef41bb6"
}
variable "redhat-8-4-minimal-amd64-3" {
default = "r006-f137ea64-0d27-4d81-afe0-353fd0557e81"
}
variable "redhat-8-6-minimal-amd64-1" {
default = "r006-1366d3e6-bf5b-49a0-b69a-8efd93cc225f"
}
variable "rocky-linux-8-6-minimal-amd64-1" {
default = "r006-7a639337-cb5b-478d-b9c4-59fd45937ec9"
}
variable "ubuntu-18-04-6-minimal-amd64-3" {
default = "r006-25cce64f-b8d7-4e86-a975-2721cfebe98b"
}
variable "ubuntu-20-04-4-minimal-amd64-1" {
default = "r006-dd164da8-c4d9-46ba-87c4-03c614f0532c"
}
variable "ubuntu-22-04-minimal-amd64-1" {
default = "r006-b5427052-bf0d-400a-a55c-e70894560b96"
}
variable "windows-server-2016-full-standard-amd64-10" {
default = "r006-d7ec6fd0-b8e2-43ae-bf1a-487782e30cc6"
}
variable "windows-server-2019-full-standard-amd64-10" {
default = "r006-44128b44-81c8-4d90-984c-c5d0363de17f"
}
variable "windows-server-2022-full-standard-amd64-4" {
default = "r006-58d2df2a-768c-413d-9262-e36a5a0f4e2d"
}
