# Generated by tabular-terraform
# Assign Floating IPs to instance of Bastion Server in zone1
resource "ibm_is_floating_ip" "bastionserver-zone1-fip" {
name = format("%s-%s-fip", var.bastionserver-name, var.zone1)
target = ibm_is_instance.bastionserver-zone1.primary_network_interface.0.id
resource_group = var.group-id
}
# Assign Floating IPs to instance of Bastion Server in zone2
resource "ibm_is_floating_ip" "bastionserver-zone2-fip" {
name = format("%s-%s-fip", var.bastionserver-name, var.zone2)
target = ibm_is_instance.bastionserver-zone2.primary_network_interface.0.id
resource_group = var.group-id
}
