# Generated by tabular-terraform
output "bastionserver-zone1-fip" {
  value = ibm_is_floating_ip.bastionserver-zone1-fip.address
}
output "bastionserver-zone2-fip" {
  value = ibm_is_floating_ip.bastionserver-zone2-fip.address
}
