---
# Basic setup of MySQL

- name: Install required pip modules
  pip:
    name:
      - PyMySQL
    state: present
    executable: pip3

- name: Ensure MySQL service is running
  systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    login_user: root
    login_password: "{{ dbpassword }}" 
    user: root
    check_implicit_admin: true
    password: "{{ dbpassword }}"
    host: localhost

- name: Create wordpress database on the server
  mysql_db:
    name: wordpress
    login_user: root
    login_password: "{{ dbpassword }}" 
    state: present

- name: Create wordpress user
  mysql_user:
    login_user: root
    login_password: "{{ dbpassword }}" 
    name: wpuser
    password: "{{ dbpassword }}"
    priv: 'wordpress.*:ALL,GRANT'
    host: '%'
    state: present
