# Generated by tabular-terraform
output "webapptier-securitygroup-id" {
  value = ibm_is_security_group.webapptier-securitygroup.id
}
output "dbtier-securitygroup-id" {
  value = ibm_is_security_group.dbtier-securitygroup.id
}
output "bastion-securitygroup-id" {
  value = ibm_is_security_group.bastion-securitygroup.id
}
output "maintenance-securitygroup-id" {
  value = ibm_is_security_group.maintenance-securitygroup.id
}
