# Generated by tabular-terraform
# Define default network ACL rules
resource "ibm_is_network_acl" "default-acl" {
name = "${var.vpc-name}-default-acl"
vpc = var.vpc-id
resource_group = ibm_resource_group.group.id
rules {
name = "${var.vpc-name}-default-deny-all-inbound"
action = "deny"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "inbound"
}
rules {
name = "${var.vpc-name}-default-deny-all-outbound"
action = "deny"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "outbound"
}
}
# Define webapptier network ACL rules
resource "ibm_is_network_acl" "webapptier-acl" {
name = "${var.vpc-name}-webapptier-acl"
vpc = var.vpc-id
resource_group = ibm_resource_group.group.id
rules {
name = "${var.vpc-name}-webapptier-icmp--all"
action = "allow"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "inbound"
icmp {
code = 0
type = 0
}
}
rules {
name = "${var.vpc-name}-webapptier-udp-user-ports"
action = "allow"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "inbound"
udp {
port_min = 1024
port_max = 65535
}
}
rules {
name = "${var.vpc-name}-webapptier-tcp-user-ports"
action = "allow"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "inbound"
tcp {
port_min = 1024
port_max = 65535
}
}
rules {
name = "${var.vpc-name}-webapptier-from-vpn-network"
action = "allow"
source = var.onprem-cidr
destination = var.address-prefix-vpc
direction = "inbound"
}
rules {
name = "${var.vpc-name}-webapptier-within-vpc"
action = "allow"
source = var.address-prefix-vpc
destination = var.address-prefix-vpc
direction = "inbound"
}
rules {
name = "${var.vpc-name}-webapptier-web-http-traffic"
action = "allow"
source = "0.0.0.0/0"
destination = var.address-prefix-vpc
direction = "inbound"
tcp {
port_min = 80
port_max = 80
}
}
rules {
name = "${var.vpc-name}-webapptier-web-ssh-traffic"
action = "allow"
source = "0.0.0.0/0"
destination = var.address-prefix-vpc
direction = "inbound"
tcp {
port_min = 22
port_max = 22
}
}
rules {
name = "${var.vpc-name}-webapptier-allow-all-outbound"
action = "allow"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "outbound"
}
}
# Define dbtier network ACL rules
resource "ibm_is_network_acl" "dbtier-acl" {
name = "${var.vpc-name}-dbtier-acl"
vpc = var.vpc-id
resource_group = ibm_resource_group.group.id
rules {
name = "${var.vpc-name}-dbtier-icmp--all"
action = "allow"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "inbound"
icmp {
code = 0
type = 0
}
}
rules {
name = "${var.vpc-name}-dbtier-udp-user-ports"
action = "allow"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "inbound"
udp {
port_min = 1024
port_max = 65535
}
}
rules {
name = "${var.vpc-name}-dbtier-tcp-user-ports"
action = "allow"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "inbound"
tcp {
port_min = 1024
port_max = 65535
}
}
rules {
name = "${var.vpc-name}-dbtier-from-vpn-network"
action = "allow"
source = var.onprem-cidr
destination = var.address-prefix-vpc
direction = "inbound"
}
rules {
name = "${var.vpc-name}-dbtier-within-vpc"
action = "allow"
source = var.address-prefix-vpc
destination = var.address-prefix-vpc
direction = "inbound"
}
rules {
name = "${var.vpc-name}-dbtier-ssh-traffic"
action = "allow"
source = "0.0.0.0/0"
destination = var.address-prefix-vpc
direction = "inbound"
tcp {
port_min = 22
port_max = 22
}
}
rules {
name = "${var.vpc-name}-dbtier-allow-all-outbound"
action = "allow"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "outbound"
}
}
# Define VPN network ACL rules
resource "ibm_is_network_acl" "vpn-acl" {
name = "${var.vpc-name}-vpn-acl"
vpc = var.vpc-id
resource_group = ibm_resource_group.group.id
rules {
name = "${var.vpc-name}-vpn-all-inbound"
action = "allow"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "inbound"
}
rules {
name = "${var.vpc-name}-vpn-allow-all-outbound"
action = "allow"
source = "0.0.0.0/0"
destination = "0.0.0.0/0"
direction = "outbound"
}
}
