# Generated by tabular-terraform
output "group-id" {
  value = ibm_resource_group.group.id
}
output "sshkey-id" {
  value = ibm_is_ssh_key.sshkey.id
}
output "webapptier-acl-id" {
  value = ibm_is_network_acl.webapptier-acl.id
}
output "dbtier-acl-id" {
  value = ibm_is_network_acl.dbtier-acl.id
}
