# Generated by tabular-terraform
# Define webapptier security group
resource "ibm_is_security_group" "webapptier-securitygroup" {
name = "${var.vpc-name}-webapptier-securitygroup"
vpc = var.vpc-id
resource_group = ibm_resource_group.group.id
}
# Define dbtier security group
resource "ibm_is_security_group" "dbtier-securitygroup" {
name = "${var.vpc-name}-dbtier-securitygroup"
vpc = var.vpc-id
resource_group = ibm_resource_group.group.id
}
# Define bastion security group
resource "ibm_is_security_group" "bastion-securitygroup" {
name = "${var.vpc-name}-bastion-securitygroup"
vpc = var.vpc-id
resource_group = ibm_resource_group.group.id
}
# Define bastion maintenance security group
resource "ibm_is_security_group" "maintenance-securitygroup" {
name = "${var.vpc-name}-maintenance-securitygroup"
vpc = var.vpc-id
resource_group = ibm_resource_group.group.id
}
# Define webapptier inbound zone1 rule
resource "ibm_is_security_group_rule" "webapptier-securitygroup-rule1" {
group = ibm_is_security_group.webapptier-securitygroup.id
direction = "inbound"
remote = var.webapptier-subnet-zone1
ip_version = "ipv4"
}
# Define webapptier inbound zone2 rule
resource "ibm_is_security_group_rule" "webapptier-securitygroup-rule2" {
group = ibm_is_security_group.webapptier-securitygroup.id
direction = "inbound"
remote = var.webapptier-subnet-zone2
ip_version = "ipv4"
}
# Define webapptier inbound onprem rule
resource "ibm_is_security_group_rule" "webapptier-securitygroup-rule3" {
group = ibm_is_security_group.webapptier-securitygroup.id
direction = "inbound"
remote = var.onprem-cidr
ip_version = "ipv4"
}
# Define webapptier inbound tcp port 80 rule
resource "ibm_is_security_group_rule" "webapptier-securitygroup-rule4" {
group = ibm_is_security_group.webapptier-securitygroup.id
direction = "inbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
tcp {
port_min = 80
port_max = 80
}
}
# Define webapptier inbound icmp type 8 rule
resource "ibm_is_security_group_rule" "webapptier-securitygroup-rule5" {
group = ibm_is_security_group.webapptier-securitygroup.id
direction = "inbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
icmp {
code = 0
type = 8
}
}
# Define webapptier outbound rule
resource "ibm_is_security_group_rule" "webapptier-securitygroup-rule6" {
group = ibm_is_security_group.webapptier-securitygroup.id
direction = "outbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
}
# Define dbtier inbound onprem rule
resource "ibm_is_security_group_rule" "dbtier-securitygroup-rule1" {
group = ibm_is_security_group.dbtier-securitygroup.id
direction = "inbound"
remote = var.onprem-cidr
ip_version = "ipv4"
}
# Define dbtier inbound zone1 rule
resource "ibm_is_security_group_rule" "dbtier-securitygroup-rule2" {
group = ibm_is_security_group.dbtier-securitygroup.id
direction = "inbound"
remote = var.dbtier-subnet-zone1
ip_version = "ipv4"
}
# Define dbtier inbound zone2 rule
resource "ibm_is_security_group_rule" "dbtier-securitygroup-rule3" {
group = ibm_is_security_group.dbtier-securitygroup.id
direction = "inbound"
remote = var.dbtier-subnet-zone2
ip_version = "ipv4"
}
# Define dbtier inbound webapptier tcp port 3306 rule
resource "ibm_is_security_group_rule" "dbtier-securitygroup-rule4" {
group = ibm_is_security_group.dbtier-securitygroup.id
direction = "inbound"
remote = ibm_is_security_group.webapptier-securitygroup.id
ip_version = "ipv4"
tcp {
port_min = 3306
port_max = 3306
}
}
# Define dbtier inbound icmp type 8 rule
resource "ibm_is_security_group_rule" "dbtier-securitygroup-rule5" {
group = ibm_is_security_group.dbtier-securitygroup.id
direction = "inbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
icmp {
code = 0
type = 8
}
}
# Define dbtier outbound rule
resource "ibm_is_security_group_rule" "dbtier-securitygroup-rule6" {
group = ibm_is_security_group.dbtier-securitygroup.id
direction = "outbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
}
# Define bastion inbound tcp port 22 rule
resource "ibm_is_security_group_rule" "bastion-securitygroup-rule1" {
group = ibm_is_security_group.bastion-securitygroup.id
direction = "inbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
tcp {
port_min = 22
port_max = 22
}
}
# Define bastion inbound icmp type 8 rule
resource "ibm_is_security_group_rule" "bastion-securitygroup-rule2" {
group = ibm_is_security_group.bastion-securitygroup.id
direction = "inbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
icmp {
type = 8
}
}
# Define bastion outbound maintenance rule
resource "ibm_is_security_group_rule" "bastion-securitygroup-rule3" {
group = ibm_is_security_group.bastion-securitygroup.id
direction = "outbound"
remote = ibm_is_security_group.maintenance-securitygroup.id
ip_version = "ipv4"
tcp {
port_min = 22
port_max = 22
}
}
# Define outbound maintenance tcp port 80 rule
resource "ibm_is_security_group_rule" "maintenance-securitygroup-rule1" {
group = ibm_is_security_group.maintenance-securitygroup.id
direction = "outbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
tcp {
port_min = 80
port_max = 80
}
}
# Define outbound maintenance tcp port 443 rule
resource "ibm_is_security_group_rule" "maintenance-securitygroup-rule2" {
group = ibm_is_security_group.maintenance-securitygroup.id
direction = "outbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
tcp {
port_min = 443
port_max = 443
}
}
# Define outbound maintenance tcp port 53 rule
resource "ibm_is_security_group_rule" "maintenance-securitygroup-rule3" {
group = ibm_is_security_group.maintenance-securitygroup.id
direction = "outbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
tcp {
port_min = 53
port_max = 53
}
}
# Define outbound maintenance udp port 53 rule
resource "ibm_is_security_group_rule" "maintenance-securitygroup-rule4" {
group = ibm_is_security_group.maintenance-securitygroup.id
direction = "outbound"
remote = "0.0.0.0/0"
ip_version = "ipv4"
udp {
port_min = 53
port_max = 53
}
}
# Define inbound maintenance tcp port 22 rule
resource "ibm_is_security_group_rule" "maintenance-securitygroup-rule5" {
group = ibm_is_security_group.maintenance-securitygroup.id
direction = "inbound"
remote = ibm_is_security_group.bastion-securitygroup.id
ip_version = "ipv4"
tcp {
port_min = 22
port_max = 22
}
}
