# Generated by tabular-terraform
variable "vpc-name" {
description = "Define vpc"
}
variable "resource-group" {
description = "Define resource group"
}
variable "webapptier-subnet-zone1" {
description = "Define webapptier subnet cidr for zone1"
}
variable "webapptier-subnet-zone2" {
description = "Define webapptier subnet cidr for zone2"
}
variable "dbtier-subnet-zone1" {
description = "Define dbtier subnet cidr for zone1"
}
variable "dbtier-subnet-zone2" {
description = "Define dbtier subnet cidr for zone2"
}
variable "ssh-public-key" {
description = "Define ssh key location for compute instances"
}
variable "address-prefix-vpc" {
description = "Define cidr block for vpc"
}
variable "onprem-cidr" {
description = "Define vpn onprem cidr"
}
variable "vpc-id" {
description = "Get vpc id"
}
