# Generated by tabular-terraform
output "vpc-id" {
value = ibm_is_vpc.vpc1.id
}
output "webapptier-subnet-zone1-id" {
value = ibm_is_subnet.webapptier-subnet-zone1.id
}
output "webapptier-subnet-zone2-id" {
value = ibm_is_subnet.webapptier-subnet-zone2.id
}
output "dbtier-subnet-zone1-id" {
value = ibm_is_subnet.dbtier-subnet-zone1.id
}
output "dbtier-subnet-zone2-id" {
value = ibm_is_subnet.dbtier-subnet-zone2.id
}
output "bastion-subnet-zone1-id" {
value = ibm_is_subnet.bastion-subnet-zone1.id
}
output "bastion-subnet-zone2-id" {
value = ibm_is_subnet.bastion-subnet-zone2.id
}
