# Generated by tabular-terraform
# Create webapp subnet in zone1
resource "ibm_is_subnet" "webapptier-subnet-zone1" {
  name            = "${var.vpc-name}-${var.zone1}-webapptier"
  vpc             = ibm_is_vpc.vpc1.id
  zone            = var.zone1
  ipv4_cidr_block = var.webapptier-subnet-zone1
  network_acl     = var.webapptier-acl-id
  public_gateway  = ibm_is_public_gateway.pubgw-zone1.id
  resource_group  = var.group-id
}
# Create db subnet in zone1
resource "ibm_is_subnet" "dbtier-subnet-zone1" {
  name            = "${var.vpc-name}-${var.zone1}-dbtier"
  vpc             = ibm_is_vpc.vpc1.id
  zone            = var.zone1
  ipv4_cidr_block = var.dbtier-subnet-zone1
  network_acl     = var.dbtier-acl-id
  public_gateway  = ibm_is_public_gateway.pubgw-zone1.id
  resource_group  = var.group-id
}
# Create webapp subnet in zone2
resource "ibm_is_subnet" "webapptier-subnet-zone2" {
  name            = "${var.vpc-name}-${var.zone2}-webapptier"
  vpc             = ibm_is_vpc.vpc1.id
  zone            = var.zone2
  ipv4_cidr_block = var.webapptier-subnet-zone2
  network_acl     = var.webapptier-acl-id
  public_gateway  = ibm_is_public_gateway.pubgw-zone2.id
  resource_group  = var.group-id
}
# Create db subnet in zone2
resource "ibm_is_subnet" "dbtier-subnet-zone2" {
  name            = "${var.vpc-name}-${var.zone2}-dbtier"
  vpc             = ibm_is_vpc.vpc1.id
  zone            = var.zone2
  ipv4_cidr_block = var.dbtier-subnet-zone2
  network_acl     = var.dbtier-acl-id
  public_gateway  = ibm_is_public_gateway.pubgw-zone2.id
  resource_group  = var.group-id
}
# Create subnet for bastion instance in zone1
resource "ibm_is_subnet" "bastion-subnet-zone1" {
  name                     = "${var.vpc-name}-${var.zone1}-bastion"
  vpc                      = ibm_is_vpc.vpc1.id
  zone                     = var.zone1
  total_ipv4_address_count = 256
  public_gateway           = ibm_is_public_gateway.pubgw-zone1.id
  resource_group           = var.group-id
}
# Create subnet for bastion instance in zone2
resource "ibm_is_subnet" "bastion-subnet-zone2" {
  name                     = "${var.vpc-name}-${var.zone2}-bastion"
  vpc                      = ibm_is_vpc.vpc1.id
  zone                     = var.zone2
  total_ipv4_address_count = 256
  public_gateway           = ibm_is_public_gateway.pubgw-zone2.id
  resource_group           = var.group-id
}
# Assign Public Gateway to zone1
resource "ibm_is_public_gateway" "pubgw-zone1" {
  name           = "${var.vpc-name}-${var.zone1}-pubgw"
  vpc            = ibm_is_vpc.vpc1.id
  zone           = var.zone1
  resource_group = var.group-id
}
# Assign Public Gateway to zone2
resource "ibm_is_public_gateway" "pubgw-zone2" {
  name           = "${var.vpc-name}-${var.zone2}-pubgw"
  vpc            = ibm_is_vpc.vpc1.id
  zone           = var.zone2
  resource_group = var.group-id
}
