# Generated by tabular-terraform
# Create new VPC
resource "ibm_is_vpc" "vpc1" {
  name           = var.vpc-name
  resource_group = var.group-id
}
# Create new address prefix in zone1
resource "ibm_is_vpc_address_prefix" "prefix1" {
  name = "zone1-cidr1"
  vpc  = ibm_is_vpc.vpc1.id
  zone = var.zone1
  cidr = var.address-prefix1
}
# Create new address prefix in zone2
resource "ibm_is_vpc_address_prefix" "prefix2" {
  name = "zone2-cidr1"
  vpc  = ibm_is_vpc.vpc1.id
  zone = var.zone2
  cidr = var.address-prefix2
}
